before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
env:
- LINT_FACTORY=true AIRBRAKE_PROJECT_ID=123456 AIRBRAKE_API_KEY=notsosecret FRILANS_FINANS_BASE_URI=https://example.com FRILANS_FINANS_CLIENT_ID=notsosecret FRILANS_FINANS_CLIENT_SECRET=notsosecret
script: script/cibuild
branches:
  only:
    - master
language: ruby
cache: bundler
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8d9e0b365480875c35af
    on_success: change
    on_failure: always
    on_start: always
rvm:
  - 2.3.0
addons:
  postgresql: "9.3"
sudo: false
