before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
install:
  - bin/setup
env:
- LINT_FACTORY=not_so_secret
script: script/cibuild
branches:
  only:
    - master
language: ruby
cache: bundler
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8d9e0b365480875c35af
    on_success: change
    on_failure: always
    on_start: always
rvm:
  - 2.3.0
addons:
  postgresql: "9.3"
sudo: false
